name: Generate Docs

on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: GenDocs
      id: GenDocs
      continue-on-error: true
      run: |
        GO111MODULE=on go get -u github.com/princjef/gomarkdoc/cmd/gomarkdoc
        ~/go/bin/gomarkdoc . > ./docs.md
        exit $(git diff docs.md | wc -c)
    - name: Debug outcome
      run: |
        echo $(git diff docs.md | wc -c)
        echo ${{ steps.GenDocs.outcome }}
    - name: Commit Changes
      if: steps.GenDocs.outcome == 'failure'
      run: |
        git config --global user.name 'AutoDocAction'
        git config --global user.email 'AudoDocAction@no-reply.com'
        git add docs.md
        git commit -m "auto generated docs"
        git push
